#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SecOC golden vector 生成器（spec §7 交叉验证策略）。

职责：
  1. 用 pycryptodome（独立于 .NET/BouncyCastle 的实现）计算 AES-128-CMAC；
  2. 先对照 NIST SP 800-38B 官方向量自证 pycryptodome 正确（不匹配即失败）；
  3. 按 spec §6.1 构造 Secured I-PDU（DataId(16bit BE) ‖ AuthData ‖ FV(32bit BE)
     作 CMAC 输入；TruncFV = FV 低 fvLen 位；TruncMAC = MAC 高 macLen 位；布局
     data ‖ TruncFV ‖ TruncMAC），生成端到端向量 JSON。

用法：python gen_vectors.py > secoc_vectors.json
运行依赖：pycryptodome（dev-only，非运行时依赖）
"""
import json
import sys

from Crypto.Cipher import AES
from Crypto.Hash import CMAC

# ---- NIST SP 800-38B 官方 AES-128 测试向量（附录 D.1 Example 1-4 = RFC 4493 TC1-TC4） ----
NIST_KEY = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
NIST_VECTORS = [
    # (消息, 官方 MAC)
    ("", "bb1d6929e95937287fa37d129b756746"),
    ("6bc1bee22e409f96e93d7e117393172a", "070a16b46b4d4144f79bdd9dd04a287c"),
    ("6bc1bee22e409f96e93d7e117393172a"
     "ae2d8a571e03ac9c9eb76fac45af8e51"
     "30c81c46a35ce411", "dfa66747de9ae63030ca32611497c827"),
    ("6bc1bee22e409f96e93d7e117393172a"
     "ae2d8a571e03ac9c9eb76fac45af8e51"
     "30c81c46a35ce411e5fbc1191a0a52ef"
     "f69f2445df4f9b17ad2b417be66c3710", "51f0bebf7e3b9d92fc49741779363cfe"),
]


def cmac(key: bytes, msg: bytes) -> bytes:
    c = CMAC.new(key, ciphermod=AES)
    c.update(msg)
    return c.digest()


def build_secured_frame(profile: dict, key: bytes, fv: int,
                        authentic_data: bytes) -> dict:
    """按 spec §6.1 构造 Secured I-PDU 并返回可复现的输入要素。"""
    fv_len, mac_len, data_id = (profile["fvLenBits"], profile["macLenBits"],
                                profile["dataIdHex"])
    fv_bits = profile["fvFullBits"]

    mac_input = (bytes.fromhex(data_id)          # DataId 16bit BE
                 + authentic_data                # AuthenticData
                 + fv.to_bytes(fv_bits // 8, "big"))  # CompleteFreshness BE
    full_mac = cmac(key, mac_input)

    truncated_fv = (fv & ((1 << fv_len) - 1)).to_bytes(fv_len // 8, "big")
    truncated_mac = full_mac[: mac_len // 8]     # 取最高有效位 = 全 MAC 前几字节
    frame = authentic_data + truncated_fv + truncated_mac

    return {
        "name": f"{profile['name']}_fv{fv}",
        "profile": profile,
        "keyHex": key.hex(),
        "fv": fv,
        "authenticDataHex": authentic_data.hex(),
        "securedFrameHex": frame.hex(),
        # 供 .NET RX 用例验证完整输入要素
        "macInputHex": mac_input.hex(),
        "fullMacHex": full_mac.hex(),
    }


def main() -> None:
    # 1) 自证：pycryptodome 与 NIST 官方向量一致
    for msg_hex, official_mac in NIST_VECTORS:
        got = cmac(NIST_KEY, bytes.fromhex(msg_hex))
        if got.hex() != official_mac:
            sys.exit(f"NIST 交叉验证失败：msg={msg_hex!r} "
                     f"got={got.hex()} expected={official_mac}")

    # 2) 端到端 Secured 帧向量（默认 profile 与样例通信矩阵对齐）
    default_profile = {
        "name": "default",               # fvLen=16 macLen=24 dataId=16bit fv=32bit
        "fvLenBits": 16, "macLenBits": 24,
        "dataIdHex": "0001", "fvFullBits": 32,
    }
    key = bytes.fromhex("00112233445566778899aabbccddeeff")
    auth_data_7 = bytes.fromhex("010500a1b2c3d4")   # 7 字节净荷（样例矩阵 TBOX 数据区长）
    auth_data_2 = bytes.fromhex("1234")             # 2 字节净荷
    auth_data_0 = b""                                # 空净荷（边界）

    frames = [
        build_secured_frame(default_profile, key, 0, auth_data_7),
        build_secured_frame(default_profile, key, 1, auth_data_7),
        build_secured_frame(default_profile, key, 65535, auth_data_7),  # 低16位全1
        build_secured_frame(default_profile, key, 65536, auth_data_7),  # 跨块
        build_secured_frame(default_profile, key, 42, auth_data_2),
        build_secured_frame(default_profile, key, 0, auth_data_0),
    ]

    doc = {
        "comment": "generated by tools/secoc-vectors/gen_vectors.py; "
                   "NIST SP 800-38B 已交叉验证",
        "nistVectors": [
            {"keyHex": NIST_KEY.hex(), "msgHex": mh, "macHex": mac}
            for mh, mac in NIST_VECTORS
        ],
        "securedFrames": frames,
    }
    print(json.dumps(doc, indent=2))


if __name__ == "__main__":
    main()