using System.Diagnostics;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
using Peak.Can.Basic.BackwardCompatibility;
using PeakCan.Host.App.Services;
using PeakCan.Host.Core;
using PeakCan.Host.Infrastructure.Channel;
using PeakCan.Host.Infrastructure.Peak;

namespace PeakCan.Host.App.ViewModels;

/// <summary>
/// Top-level shell view model: status bar, channel-probe / connect toolbar,
/// and the Open-DBC menu command. Tasks 13-17 will wire the ContentControl
/// in <c>AppShell.xaml</c> to per-tab view models and route the DBC
/// command into <c>DbcService</c>; this VM only owns the chrome.
/// <para>
/// <b>Hardware probe (MVP):</b> per the inline amendment, this class
/// hard-codes handle <c>0x51</c> (PCAN-USB FD first channel) and probes
/// it with <c>PCANBasic.Initialize</c>. A non-error status means the
/// channel is reachable and <see cref="ConnectCommand"/> is enabled.
/// Full multi-channel enumeration is v1.1.
/// </para>
/// <para>
/// <b>Thread-safety:</b> <see cref="ConnectAsync"/> captures the WPF
/// <c>DispatcherSynchronizationContext</c> at the await site via
/// <c>ConfigureAwait(true)</c>; the property setters below it run on the
/// UI thread because the await resumed there. CommunityToolkit.Mvvm's
/// generated <c>SetProperty</c> itself does NOT marshal — it just fires
/// <c>PropertyChanged</c>. The dispatcher affinity comes from the captured
/// context, not from the source generator.
/// </para>
/// </summary>
public sealed partial class AppShellViewModel : ObservableObject
{
    /// <summary>
    /// PEAK PCAN-USB FD first channel handle. Mirrors
    /// <see cref="Composition.AppHostBuilder.PcanUsbFdFirstHandle"/>; kept
    /// here as a local constant so the VM does not pull in App composition
    /// for a single number.
    /// </summary>
    private const ushort PcanUsbFdFirstHandle = 0x51;

    private readonly ChannelRouter _router;
    private readonly ILogger<AppShellViewModel> _logger;
    private readonly SendService _sendService;

    /// <summary>Active channel after a successful Connect command; null otherwise.</summary>
    private PeakCanChannel? _activeChannel;

    /// <summary>Last known probe result. Connect is enabled only when this is "USB1 ...".</summary>
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(ConnectCommand))]
    private string _channelList = "(click Probe to detect)";

    [ObservableProperty]
    private string _statusMessage = "Ready";

    [ObservableProperty]
    private string _connectionState = "Disconnected";

    /// <summary>
    /// True after a successful Connect until a future Disconnect (v1.1).
    /// The toolbar binds to this for the enabled state of the
    /// Connect button; bound via the partial property generated by
    /// CommunityToolkit.Mvvm.
    /// </summary>
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(ConnectCommand))]
    private bool _isConnected;

    /// <summary>
    /// The Trace tab's view model. Task 13 embeds the
    /// <see cref="Views.TraceView"/> directly into <c>AppShell.xaml</c>'s
    /// <c>MainArea</c> via this property; Tasks 14-17 will introduce a
    /// tab-switching layer (the AppShell's <c>ContentControl</c> will
    /// switch to a <c>ContentPresenter</c> bound to a selected-tab VM).
    /// </summary>
    public TraceViewModel TraceViewModel { get; }

    /// <summary>
    /// The manual-send form's service. The shell publishes the connected
    /// <see cref="ICanChannel"/> onto it after a successful
    /// <see cref="ConnectAsync"/> so the send tab (Task 14) and any
    /// future sender can transmit without re-initializing the hardware.
    /// Exposed publicly so tests can assert the wiring without spinning
    /// up the full WPF shell.
    /// </summary>
    public SendService SendService => _sendService;

    public AppShellViewModel(
        ChannelRouter router,
        ILogger<AppShellViewModel> logger,
        TraceViewModel traceViewModel,
        SendService sendService)
    {
        _router = router ?? throw new ArgumentNullException(nameof(router));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        TraceViewModel = traceViewModel ?? throw new ArgumentNullException(nameof(traceViewModel));
        _sendService = sendService ?? throw new ArgumentNullException(nameof(sendService));
    }

    [RelayCommand]
    private void OpenDbc()
    {
        // Wired into DbcService in Task 15. For now, surface in the status
        // bar so the menu command is observable to the user and to tests.
        StatusMessage = "Open DBC clicked (Task 15)";
        LogOpenDbcInvoked(_logger);
    }

    [RelayCommand(CanExecute = nameof(CanEnumerateChannels))]
    private void EnumerateChannels()
    {
        // MVP probe: call PCANBasic.Initialize on the first PCAN-USB FD
        // handle. Success means the device responded. Uninitialize right
        // away — Connect will re-Initialize on the actual baud rate.
        // We deliberately do NOT enumerate multi-channel yet (v1.1).
        try
        {
            var status = PCANBasic.Initialize(PcanUsbFdFirstHandle, TPCANBaudrate.PCAN_BAUD_1M);
            if (PeakErrorMapper.IsOk((uint)status))
            {
                ChannelList = "USB1 (1 Mbps default)";
                StatusMessage = "PEAK PCAN-USB FD detected on USB1";
                LogProbeOk(_logger, PcanUsbFdFirstHandle);
                // Best-effort uninit so we don't leave the channel held
                // open between probe and connect.
                try { PCANBasic.Uninitialize(PcanUsbFdFirstHandle); }
                catch (Exception uninitEx)
                {
                    LogProbeUninitFailed(_logger, PcanUsbFdFirstHandle, uninitEx);
                }
            }
            else
            {
                var (code, msg) = PeakErrorMapper.ToErrorCode((uint)status);
                ChannelList = $"No PEAK hardware detected: {msg}";
                StatusMessage = $"Probe failed: {msg}";
                LogProbeFailed(_logger, PcanUsbFdFirstHandle, code, msg);
            }
        }
        catch (Exception ex)
        {
            // The PEAK SDK occasionally throws (DllNotFound, etc.) on
            // machines without the driver installed. Surface to the user
            // and log; never let the RelayCommand swallow silently.
            ChannelList = $"No PEAK hardware detected: {ex.Message}";
            StatusMessage = $"Probe exception: {ex.GetType().Name}";
            LogProbeThrew(_logger, PcanUsbFdFirstHandle, ex);
        }
    }

    private bool CanEnumerateChannels() => !IsConnected;

    // STRING-COUPLED: the predicate below matches the probe-success message
    // emitted by EnumerateChannels at the call site above ("USB1 ..."). A
    // future change to the probe output (localization, multi-channel) must
    // update this predicate in lockstep; the AppShellViewModelTests
    // covers the CanExecute=true path with this exact sentinel.
    private bool CanConnect() => !IsConnected && ChannelList.StartsWith("USB1", StringComparison.Ordinal);

    [RelayCommand(CanExecute = nameof(CanConnect))]
    private async Task ConnectAsync()
    {
        ConnectionState = "Connecting...";
        StatusMessage = "Connecting to USB1 (CAN FD 1 Mbps)";
        try
        {
            var channel = new PeakCanChannel(new ChannelId(PcanUsbFdFirstHandle));
            var result = await channel.ConnectAsync(BaudRate.CanFd1Mbps, fd: true).ConfigureAwait(true);
            if (result.IsSuccess)
            {
                _activeChannel = channel;
                _router.RegisterChannel(channel);
                // Set IsConnected=true BEFORE publishing the channel to
                // SendService so that any binding observer sees "connected"
                // and an available channel atomically — no window where
                // Send can fire against a channel the UI still considers
                // disconnected. [ObservableProperty] setters fire
                // PropertyChanged in order; this ordering keeps the
                // Send button's CanExecute (when wired) consistent.
                IsConnected = true;
                ConnectionState = "Connected to USB1 (CAN FD 1 Mbps)";
                StatusMessage = "Connected";
                _sendService.ActiveChannel = channel;
                LogConnectOk(_logger, PcanUsbFdFirstHandle);
            }
            else
            {
                ConnectionState = "Disconnected";
                _sendService.ActiveChannel = null;
                var err = result.Error!;
                StatusMessage = $"Connect failed: {err.Code} {err.Message}";
                LogConnectFailed(_logger, PcanUsbFdFirstHandle, err.Code, err.Message);
                // PeakCanChannel ctor allocates a CancellationTokenSource
                // (used by the read loop). On a failed Connect the channel
                // never acquires the hardware, so the safe teardown is to
                // dispose it now rather than wait for GC.
                await channel.DisposeAsync().ConfigureAwait(true);
            }
        }
        catch (Exception ex)
        {
            ConnectionState = "Disconnected";
            StatusMessage = $"Connect exception: {ex.GetType().Name}";
            LogConnectThrew(_logger, PcanUsbFdFirstHandle, ex);
        }
    }

    // LoggerMessage source-generated helpers silence CA1848 (use LoggerMessage
    // source generators) and CA1873 (avoid expensive arg computation in
    // disabled loggers). The methods are deliberately not called from hot
    // paths; their only call site is the VM commands.

    [LoggerMessage(Level = LogLevel.Information, Message = "Open DBC menu invoked")]
    private static partial void LogOpenDbcInvoked(ILogger logger);

    [LoggerMessage(Level = LogLevel.Information, Message = "Probe OK on handle 0x{Handle:X2}")]
    private static partial void LogProbeOk(ILogger logger, ushort handle);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Probe uninit failed on handle 0x{Handle:X2}")]
    private static partial void LogProbeUninitFailed(ILogger logger, ushort handle, Exception ex);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Probe failed on handle 0x{Handle:X2}: {Code} {Message}")]
    private static partial void LogProbeFailed(ILogger logger, ushort handle, ErrorCode code, string message);

    [LoggerMessage(Level = LogLevel.Error, Message = "Probe threw on handle 0x{Handle:X2}")]
    private static partial void LogProbeThrew(ILogger logger, ushort handle, Exception ex);

    [LoggerMessage(Level = LogLevel.Information, Message = "Connect OK on handle 0x{Handle:X2}")]
    private static partial void LogConnectOk(ILogger logger, ushort handle);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Connect failed on handle 0x{Handle:X2}: {Code} {Message}")]
    private static partial void LogConnectFailed(ILogger logger, ushort handle, ErrorCode code, string message);

    [LoggerMessage(Level = LogLevel.Error, Message = "Connect threw on handle 0x{Handle:X2}")]
    private static partial void LogConnectThrew(ILogger logger, ushort handle, Exception ex);
}
