using System.Diagnostics;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
using PeakCan.Host.App.Services;
using PeakCan.Host.App.Views;
using PeakCan.Host.Core;
using PeakCan.Host.Infrastructure.Channel;

namespace PeakCan.Host.App.ViewModels;

/// <summary>
/// Top-level shell view model: status bar, channel-probe / connect toolbar,
/// the Open-DBC menu command, and the per-tab view cache that drives the
/// <c>MainArea</c> <see cref="System.Windows.Controls.ContentControl"/>.
/// <para>
/// <b>View caching (Task 15):</b> the three tab views (<see cref="TraceView"/>,
/// <see cref="DbcView"/>, <see cref="SendView"/>) are instantiated once in
/// the constructor and swapped via <see cref="CurrentView"/>. Reusing the
/// view instances preserves DataGrid virtualization state across switches
/// (scroll position, selection) and avoids paying the DataGrid layout cost
/// on every menu click. Each view's <c>DataContext</c> is bound at
/// construction time so XAML bindings resolve without any per-click
/// DataContext plumbing.
/// </para>
/// <para>
/// <b>Hardware probe (MVP):</b> per the inline amendment, this class
/// hard-codes handle <c>0x51</c> (PCAN-USB FD first channel) and probes
/// it with <c>PCANBasic.Initialize</c>. A non-error status means the
/// channel is reachable and <see cref="ConnectCommand"/> is enabled.
/// Full multi-channel enumeration is v1.1.
/// </para>
/// <para>
/// <b>Thread-safety:</b> <see cref="ConnectAsync"/> captures the WPF
/// <c>DispatcherSynchronizationContext</c> at the await site via
/// <c>ConfigureAwait(true)</c>; the property setters below it run on the
/// UI thread because the await resumed there. CommunityToolkit.Mvvm's
/// generated <c>SetProperty</c> itself does NOT marshal — it just fires
/// <c>PropertyChanged</c>. The dispatcher affinity comes from the captured
/// context, not from the source generator.
/// </para>
/// </summary>
public sealed partial class AppShellViewModel : ObservableObject
{
    /// <summary>
    /// PEAK PCAN-USB FD first channel handle. Mirrors
    /// <see cref="Composition.AppHostBuilder.PcanUsbFdFirstHandle"/>; kept
    /// here as a local constant so the VM does not pull in App composition
    /// for a single number.
    /// </summary>
    private const ushort PcanUsbFdFirstHandle = 0x51;
    // BaudRate is a readonly record struct, not a literal type, so it
    // cannot be a `const` in C#. `static readonly` gives us the same
    // named, class-level binding the task asked for (see ICanChannel.cs
    // preset table) without a runtime cost.
    private static readonly BaudRate DefaultBaudRate = BaudRate.CanFd1Mbps;
    private const bool DefaultFd = true;

    private readonly ChannelRouter _router;
    private readonly ILogger<AppShellViewModel> _logger;
    private readonly SendService _sendService;
    private readonly IChannelProbe _channelProbe;
    private readonly IChannelFactory _channelFactory;
    private readonly TraceViewModel _traceViewModel;
    private readonly DbcViewModel _dbcViewModel;
    private readonly SendViewModel _sendViewModel;
    private readonly SignalViewModel _signalViewModel;
    private readonly StatsViewModel _statsViewModel;

    // View instances are created lazily on the first Show command so the
    // shell's ctor stays STA-free (xunit runs on MTA). Production callers
    // always resolve the VM from the WPF STA thread (App.OnStartup), so
    // the first Show happens on STA and the WPF UserControl ctor succeeds.
    private TraceView? _traceView;
    private DbcView? _dbcView;
    private SendView? _sendView;
    private SignalView? _signalView;
    private StatsView? _statsView;

    /// <summary>Active channel after a successful Connect command; null otherwise.</summary>
    private ICanChannel? _activeChannel;

    /// <summary>Last known probe result. Connect is enabled only when this is "USB1 ...".</summary>
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(ConnectCommand))]
    private string _channelList = "(click Probe to detect)";

    [ObservableProperty]
    private string _statusMessage = "Ready";

    [ObservableProperty]
    private string _connectionState = "Disconnected";

    /// <summary>
    /// True after a successful Connect until a future Disconnect (v1.1).
    /// The toolbar binds to this for the enabled state of the
    /// Connect button; bound via the partial property generated by
    /// CommunityToolkit.Mvvm.
    /// </summary>
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(ConnectCommand))]
    [NotifyCanExecuteChangedFor(nameof(DisconnectCommand))]
    private bool _isConnected;

    /// <summary>
    /// The view currently shown in <c>AppShell.xaml</c>'s <c>MainArea</c>.
    /// Switched by the View menu (Trace / DBC / Send) and by the
    /// Open-DBC menu command. The instance is cached — see class doc.
    /// </summary>
    [ObservableProperty]
    private object? _currentView;

    /// <summary>Manual-send service for shell-to-send tab wiring (Task 14).</summary>
    public SendService SendService => _sendService;

    public AppShellViewModel(
        ChannelRouter router,
        ILogger<AppShellViewModel> logger,
        TraceViewModel traceViewModel,
        SendService sendService,
        IChannelProbe channelProbe,
        IChannelFactory channelFactory,                    // NEW (T3)
        DbcViewModel dbcViewModel,
        SendViewModel sendViewModel,
        SignalViewModel signalViewModel,
        StatsViewModel statsViewModel)
    {
        _router = router ?? throw new ArgumentNullException(nameof(router));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _traceViewModel = traceViewModel ?? throw new ArgumentNullException(nameof(traceViewModel));
        _sendService = sendService ?? throw new ArgumentNullException(nameof(sendService));
        _channelProbe = channelProbe ?? throw new ArgumentNullException(nameof(channelProbe));
        _channelFactory = channelFactory ?? throw new ArgumentNullException(nameof(channelFactory));
        _dbcViewModel = dbcViewModel ?? throw new ArgumentNullException(nameof(dbcViewModel));
        _sendViewModel = sendViewModel ?? throw new ArgumentNullException(nameof(sendViewModel));
        _signalViewModel = signalViewModel ?? throw new ArgumentNullException(nameof(signalViewModel));
        _statsViewModel = statsViewModel ?? throw new ArgumentNullException(nameof(statsViewModel));

        // View instances are lazily created on the first Show command.
        // The default CurrentView is null until ShowTrace runs (which
        // happens in production via AppShell.xaml.cs's SourceInitialized
        // handler). See the field XML doc above for the STA rationale.
        //
        // ctor 9-arg explosion flagged for AppDependencies refactor in
        // the Task 17+18 wrap-up (bundle VM deps into a single record).
    }

    [RelayCommand]
    private void OpenDbc()
    {
        // Task 15: the File ▸ Open DBC... menu item routes into the DBC
        // tab. The actual file-open dialog is owned by the per-view
        // Open button inside DbcViewModel.OpenAsync; the menu item
        // only navigates so the user sees the right surface.
        CurrentView = GetOrCreateDbcView();
        LogOpenDbcInvoked(_logger);
    }

    [RelayCommand]
    private void ShowTrace()
    {
        if (_traceView == null)
        {
            _traceView = new TraceView { DataContext = _traceViewModel };
            // First-show sets the default tab so the very first render
            // after VM construction lands on the trace grid.
            if (CurrentView == null) CurrentView = _traceView;
        }
        CurrentView = _traceView;
    }

    [RelayCommand]
    private void ShowDbc() => CurrentView = GetOrCreateDbcView();

    [RelayCommand]
    private void ShowSend()
    {
        if (_sendView == null)
        {
            _sendView = new SendView { DataContext = _sendViewModel };
            if (CurrentView == null) CurrentView = _sendView;
        }
        CurrentView = _sendView;
    }

    [RelayCommand]
    private void ShowSignals()
    {
        // Task 16: Signal tab (DBC-decoded live signals). Mirrors
        // ShowSend: lazily create the view on first Show so the shell
        // ctor stays STA-free; reuse the same instance thereafter so
        // DataGrid virtualization state survives menu round-trips.
        if (_signalView == null)
        {
            _signalView = new SignalView { DataContext = _signalViewModel };
            if (CurrentView == null) CurrentView = _signalView;
        }
        CurrentView = _signalView;
    }

    [RelayCommand]
    private void ShowStats()
    {
        // Task 17: Stats tab (1 Hz OxyPlot charts). Same lazy-view
        // pattern as ShowSignals / ShowSend. The StatsView hosts an
        // OxyPlot.PlotView bound to StatsViewModel.PlotModel; the
        // StatisticsService pushes snapshots at 1 Hz on its own thread
        // and the VM marshals to the UI dispatcher.
        if (_statsView == null)
        {
            _statsView = new StatsView { DataContext = _statsViewModel };
            if (CurrentView == null) CurrentView = _statsView;
        }
        CurrentView = _statsView;
    }

    private DbcView GetOrCreateDbcView() => _dbcView ??= new DbcView { DataContext = _dbcViewModel };

    [RelayCommand(CanExecute = nameof(CanEnumerateChannels))]
    private void EnumerateChannels()
    {
        // Task 18: the probe was moved out of the VM into
        // <see cref="IChannelProbe"/> so the App assembly has no
        // PEAK SDK dependency (enforced by NetArchTest rule 3). The
        // VM only knows the contract: hand the probe a handle, get
        // back a structured result. The user-visible "USB1 ..." /
        // "No PEAK hardware detected" strings stay here because they
        // are UI formatting (and STRING-COUPLED with CanConnect).
        var result = _channelProbe.Probe(PcanUsbFdFirstHandle);
        if (result.Ok)
        {
            ChannelList = "USB1 (1 Mbps default)";
            StatusMessage = result.Message;
            LogProbeOk(_logger, PcanUsbFdFirstHandle);
        }
        else
        {
            ChannelList = $"No PEAK hardware detected: {result.Message}";
            StatusMessage = result.Message;
            LogProbeThrew(_logger, PcanUsbFdFirstHandle,
                new InvalidOperationException(result.Message));
        }
    }

    private bool CanEnumerateChannels() => !IsConnected;

    // STRING-COUPLED: the predicate below matches the probe-success message
    // emitted by EnumerateChannels at the call site above ("USB1 ..."). A
    // future change to the probe output (localization, multi-channel) must
    // update this predicate in lockstep; the AppShellViewModelTests
    // covers the CanExecute=true path with this exact sentinel.
    private bool CanConnect() => !IsConnected && ChannelList.StartsWith("USB1", StringComparison.Ordinal);

    [RelayCommand(CanExecute = nameof(CanConnect))]
    private async Task ConnectAsync()
    {
        ConnectionState = "Connecting...";
        StatusMessage = "Connecting to USB1 (CAN FD 1 Mbps)";
        try
        {
            var channel = _channelFactory.Create(new ChannelId(PcanUsbFdFirstHandle));
            var result = await channel.ConnectAsync(DefaultBaudRate, fd: DefaultFd).ConfigureAwait(true);
            if (result.IsSuccess)
            {
                _activeChannel = channel;
                _router.RegisterChannel(channel);
                // Set IsConnected=true BEFORE publishing the channel to
                // SendService so that any binding observer sees "connected"
                // and an available channel atomically — no window where
                // Send can fire against a channel the UI still considers
                // disconnected. [ObservableProperty] setters fire
                // PropertyChanged in order; this ordering keeps the
                // Send button's CanExecute (when wired) consistent.
                IsConnected = true;
                ConnectionState = "Connected to USB1 (CAN FD 1 Mbps)";
                StatusMessage = "Connected";
                _sendService.ActiveChannel = channel;
                LogConnectOk(_logger, PcanUsbFdFirstHandle);
            }
            else
            {
                ConnectionState = "Disconnected";
                _sendService.ActiveChannel = null;
                var err = result.Error!;
                StatusMessage = $"Connect failed: {err.Code} {err.Message}";
                LogConnectFailed(_logger, PcanUsbFdFirstHandle, err.Code, err.Message);
                // PeakCanChannel ctor allocates a CancellationTokenSource
                // (used by the read loop). On a failed Connect the channel
                // never acquires the hardware, so the safe teardown is to
                // dispose it now rather than wait for GC.
                await channel.DisposeAsync().ConfigureAwait(true);
            }
        }
        catch (Exception ex)
        {
            ConnectionState = "Disconnected";
            StatusMessage = $"Connect exception: {ex.GetType().Name}";
            LogConnectThrew(_logger, PcanUsbFdFirstHandle, ex);
        }
    }

    [RelayCommand(CanExecute = nameof(CanDisconnect))]
    private async Task DisconnectAsync()
    {
        if (!IsConnected || _activeChannel is null) return;
        StatusMessage = $"Disconnecting from {DefaultBaudRate.Name}";
        ConnectionState = "Disconnecting...";
        try
        {
            await _activeChannel.DisconnectAsync().ConfigureAwait(true);
            _router.UnregisterChannel(_activeChannel);
            _sendService.ActiveChannel = null;
            IsConnected = false;
            ConnectionState = "Disconnected";
            StatusMessage = "Disconnected";
            LogDisconnectOk(_logger, PcanUsbFdFirstHandle);
        }
        catch (Exception ex)
        {
            // DisconnectAsync swallows hardware failures per its own contract;
            // any exception here is therefore unexpected. Surface it as a
            // status message so the operator is not stuck in "Disconnecting".
            // Reset every piece of state the success path resets: leaving
            // IsConnected=true keeps the Disconnect button enabled against a
            // dead channel; leaving the channel on the router keeps frames
            // being routed to it; leaving SendService.ActiveChannel set
            // targets the next manual send at a dead channel. Order matches
            // the success path (UnregisterChannel → ActiveChannel=null →
            // IsConnected=false) so the two paths produce identical state
            // transitions from an observer's point of view.
            _router.UnregisterChannel(_activeChannel);
            _sendService.ActiveChannel = null;
            IsConnected = false;
            ConnectionState = "Disconnected";
            StatusMessage = $"Disconnect exception: {ex.GetType().Name}";
            LogDisconnectThrew(_logger, PcanUsbFdFirstHandle, ex);
        }
        finally
        {
            _activeChannel = null;
        }
    }

    private bool CanDisconnect() => IsConnected;

    // LoggerMessage source-generated helpers silence CA1848 (use LoggerMessage
    // source generators) and CA1873 (avoid expensive arg computation in
    // disabled loggers). The methods are deliberately not called from hot
    // paths; their only call site is the VM commands.

    [LoggerMessage(Level = LogLevel.Information, Message = "Open DBC menu invoked")]
    private static partial void LogOpenDbcInvoked(ILogger logger);

    [LoggerMessage(Level = LogLevel.Information, Message = "Probe OK on handle 0x{Handle:X2}")]
    private static partial void LogProbeOk(ILogger logger, ushort handle);

    [LoggerMessage(Level = LogLevel.Error, Message = "Probe threw on handle 0x{Handle:X2}")]
    private static partial void LogProbeThrew(ILogger logger, ushort handle, Exception ex);

    [LoggerMessage(Level = LogLevel.Information, Message = "Connect OK on handle 0x{Handle:X2}")]
    private static partial void LogConnectOk(ILogger logger, ushort handle);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Connect failed on handle 0x{Handle:X2}: {Code} {Message}")]
    private static partial void LogConnectFailed(ILogger logger, ushort handle, ErrorCode code, string message);

    [LoggerMessage(Level = LogLevel.Error, Message = "Connect threw on handle 0x{Handle:X2}")]
    private static partial void LogConnectThrew(ILogger logger, ushort handle, Exception ex);

    [LoggerMessage(Level = LogLevel.Information, Message = "Disconnect OK on handle 0x{Handle:X2}")]
    private static partial void LogDisconnectOk(ILogger logger, ushort handle);

    [LoggerMessage(Level = LogLevel.Error, Message = "Disconnect threw on handle 0x{Handle:X2}")]
    private static partial void LogDisconnectThrew(ILogger logger, ushort handle, Exception ex);
}
